data: tuple[int, str, str, list[int]] = [
	(1, "Tokino Sora", "Achieve a cumulative score of 100,000", []),
	(2, "Roboco", "Achieve 8 chains", []),
	(3, "AZKi", "Achieve a cumulative score of 70,000", []),
	(4, "Sakura Miko", "Make the biggest treasure a total of 3 times", []),
	(5, "Hoshimachi Suisei", "Achieve a score of 6,000 in a single play", []),
	(6, "Aki Rosenthal", "Achieve a cumulative score of 10,000", []),
	(7, "Akai Haato", "Total 250 chains", []),
	(8, "Shirakami Fubuki", "Achieve a cumulative score of 30,000", []),
	(9, "Natsuiro Matsuri", "Combine characters 4,000 times in total", []),
	(10, "Minato Aqua", "Achieve a score of 4,500 in a single play", []),
	(11, "Murasaki Shion", "Set [Minato Aqua] as the biggest treasure and create it 1 time", [10]),
	(12, "Nakiri Ayame", "Achieve a cumulative score of 50,000", []),
	(13, "Yuzuki Choco", "Make the biggest treasure a total of 2 times", []),
	(14, "Oozora Subaru", "Achieve 7 chains", []),
	(15, "Ookami Mio", "Make the biggest treasure a total of 1 time", []),
	(16, "Nekomata Okayu", "Combine characters 2,000 times in total", []),
	(17, "Inugami Korone", "Set [Nekomata Okayu] as the biggest treasure and create it 1 time", [16]),
	(32, "Houshou Marine", "Achieve a cumulative score of 171,717", []),
	(18, "Laplus Darknesss", "Achieve 9 chains", []),
	(19, "Takane Lui", "Set [La+ Darknesss] as the biggest treasure and create it 1 time", [18]),
	(20, "Hakui Koyori", "Set [Usada Pekora] as the biggest treasure and create it 2 times", []),
	(21, "Sakamata Chloe", "Set [La+ Darknesss] as the biggest treasure and create it 3 times", [18]),
	(22, "Kazama Iroha", "Set [La+ Darknesss] as the biggest treasure and create it 4 times", [18]),
	(23, "Hiodoshi Ao", "Set [Kazama Iroha] as the biggest treasure and create it 2 times", [22]),
	(28, "Otonose Kanade", "Set [Hiodoshi Ao] as the biggest treasure and create it 2 times", [23]),
	(29, "Ichijou Ririka", "Set [Otonose Kanade] as the biggest treasure and create it 2 times", [28]),
	(30, "Juufuutei Raden", "Set [Ichijou Ririka] as the biggest treasure and create it 2 times", [29]),
	(31, "Todoroki Hajime", "Set [Juufuutei Raden] as the biggest treasure and create it 2 times", [30]),
	(38, "Ayunda Risu", "Set [Inugami Korone] in your deck and make the biggest treasure 2 times", [17]),
	(39, "Moona Hoshinova", "Set [Usada Pekora] in your deck and achieve 5,000 points in a single play", []),
	(40, "Airani Iofifteen", "Set [Tokino Sora] in your deck and achieve a total of 60,000 points", [1]),
	(46, "Kureiji Ollie", "Set [Natsuiro Matsuri] in your deck and achieve 7 chains", [9]),
	(47, "Anya Melfissa", "Set [Yukihana Lamy] in your deck and combine characters 1,000 times in total", []),
	(48, "Pavolia Reine", "Set [Watson Amelia] in your deck and achieve a total of 30,000 points", [37]),
	(59, "Vestia Zeta", "Set [Kobo Kanaeru] in your deck and make the biggest treasure", [61]),
	(60, "Kaela Kovalskia", "Set [Sakura Miko] in your deck and combine characters 500 times in total", [4]),
	(61, "Kobo Kanaeru", "Set [Kureiji Ollie] in your deck and achieve a total of 300 chains", [46]),
	(33, "Mori Calliope", "Make the biggest treasure 2 times in a row in three gameplay sessions", []),
	(34, "Takanashi Kiara", "Set [Mori Calliope] in your deck and achieve 9 chains", [33]),
	(35, "Ninomae Inanis", "Achieve a score of 4,500 3 times in a row in three gameplay sessions", []),
	(36, "Gawr Gura", "Set all 5 members of [Gen 2] in your deck and combine characters 1,000 times in total", [10, 11, 12, 13, 14]),
	(37, "Watson Amelia", "Set all 4 members of [Gen 1] in your deck and achieve a total of 30,000 points", [6, 7, 8, 9]),
	(41, "IRyS", "Set [Shiranui Flare] in your deck and achieve 3,000 points in a single play", []),
	(42, "Ceres Fauna", "Set [Tsunomaki Watame] as the biggest treasure and create it 2 times", []),
	(43, "Ouro Kronii", "Set [Nanashi Mumei] in your deck and achieve a total of 20,000 points", [44]),
	(44, "Nanashi Mumei", "Set [Akai Haato] as the biggest treasure and create it 2 times", [7]),
	(45, "Hakos Baelz", "Achieve a score of 2,500 4 times in a row in three gameplay sessions", []),
	(54, "Shiori Novella", "Set [Koseki Bijou] in your deck and achieve 3,500 points in a single play", [55]),
	(55, "Koseki Bijou", "Set [Kaela Kovalskia] in your deck and combine characters 300 times in total", [60]),
	(56, "Nerissa Ravencroft", "Set [Takanashi Kiara] in your deck and achieve 7 chains", [34]),
	(57, "Fuwawa Abyssgard", "Set [Yukihana Lamy] in your deck and achieve a total of 10,000 points", []),
	(58, "Mococo Abyssgard", "Set [Hakui Koyori] in your deck and achieve a total of 10,000 points", [20]),
	(62, "Elizabeth Rose Bloodflame", "Set all 5 members of [Advent] in your deck and achieve a total of 10,000 points", [54, 55, 56, 57, 58]),
	(63, "Gigi Murin", "Set [Koseki Bijou] in your deck and achieve a total of 200 chains", [55]),
	(64, "Cecilia Immergreen", "Set [Amane Kanata] in your deck and make the biggest treasure", []),
	(65, "Raora Panthera", "Set 2 members of [FUWAMOCO] in your deck and combine characters 300 times in total", [57, 58]),
	(49, "Isaki Riona", "Achieve a score of 1,800 2 times in a row in three gameplay sessions", []),
	(50, "Koganei Niko", "Set [Isaki Riona] in your deck and achieve a total of 5,000 points", [49]),
	(51, "Mizumiya Su", "Set [Koganei Niko] in your deck and combine characters 100 times in total", [50]),
	(52, "Rindo Chihaya", "Set [Mizumiya Su] in your deck and achieve 6 chains", [51]),
	(53, "Kikirara Vivi", "Set [Rindo Chihaya] in your deck and make the biggest treasure", [52]),
]
