data: tuple[int, int, list[str]] = [
	(1, 1, ["tokino", "sora"]),
	(2, 2, ["robocosan", "roboco"]),
	(3, 3, ["azki"]),
	(4, 4, ["sakura", "miko"]),
	(5, 5, ["hoshimachi", "suisei"]),
	(6, 6, ["aki", "rosenthal"]),
	(7, 7, ["akai", "haato", "haachama"]),
	(8, 8, ["shirakami", "fubuki"]),
	(9, 9, ["natsuiro", "matsuri"]),
	(10, 10, ["minato", "aqua"]),
	(11, 11, ["murasaki", "shion"]),
	(12, 12, ["nakiri", "ayame"]),
	(13, 13, ["yuzuki", "choco"]),
	(14, 14, ["oozora", "subaru"]),
	(15, 15, ["ookami", "mio"]),
	(16, 16, ["nekomata", "okayu"]),
	(17, 17, ["inugami", "korone"]),
	(18, 0, ["usada", "pekora"]),
	(19, 0, ["shiranui", "flare"]),
	(20, 0, ["shirogane", "noel"]),
	(21, 32, ["houshou", "marine"]),
	(22, 0, ["amane", "kanata"]),
	(23, 0, ["tsunomaki", "watame"]),
	(24, 0, ["tokoyami", "towa"]),
	(25, 0, ["himemori", "luna"]),
	(26, 0, ["yukihana", "lamy"]),
	(27, 0, ["momosuzu", "nene"]),
	(28, 0, ["shishiro", "botan"]),
	(29, 0, ["omaru", "polka"]),
	(30, 18, ["laplus", "darknesss", "la"]),
	(31, 19, ["takane", "lui"]),
	(32, 20, ["hakui", "koyori"]),
	(33, 21, ["sakamata", "chloe"]),
	(34, 22, ["kazama", "iroha"]),
	(35, 23, ["hiodoshi", "ao"]),
	(36, 28, ["otonose", "kanade"]),
	(37, 29, ["ichijou", "ririka"]),
	(38, 30, ["juufuutei", "raden"]),
	(39, 31, ["todoroki", "hajime", "bancho"]),
	(40, 38, ["ayunda", "risu"]),
	(41, 39, ["moona", "hoshinova"]),
	(42, 40, ["airani", "iofifteen", "iofi"]),
	(43, 46, ["kureiji", "ollie"]),
	(44, 47, ["anya", "melfissa"]),
	(45, 48, ["pavolia", "reine"]),
	(46, 59, ["vestia", "zeta"]),
	(47, 60, ["kaela", "kovalskia"]),
	(48, 61, ["kobo", "kanaeru"]),
	(49, 33, ["mori", "calliope"]),
	(50, 34, ["takanashi", "kiara"]),
	(51, 35, ["ninomae", "inanis", "ina"]),
	(52, 36, ["gawr", "gura"]),
	(53, 37, ["watson", "amelia"]),
	(54, 41, ["irys"]),
	(55, 42, ["ceres", "fauna"]),
	(56, 43, ["ouro", "kronii"]),
	(57, 44, ["nanashi", "mumei"]),
	(58, 45, ["hakos", "baelz", "bae"]),
	(59, 54, ["shiori", "novella"]),
	(60, 55, ["koseki", "bijou", "biboo"]),
	(61, 56, ["nerissa", "ravencroft"]),
	(62, 57, ["fuwawa", "abyssgard"]),
	(63, 58, ["mococo", "abyssgard"]),
	(64, 62, ["elizabeth", "rose", "bloodflame", "erb"]),
	(65, 63, ["gigi", "murin", "gg"]),
	(66, 64, ["cecilia", "immergreen", "cc"]),
	(67, 65, ["raora", "panthera"]),
	(68, 49, ["isaki", "riona"]),
	(69, 50, ["koganei", "niko"]),
	(70, 51, ["mizumiya", "su"]),
	(71, 52, ["rindo", "chihaya"]),
	(72, 53, ["kikirara", "vivi"]),
]

name_to_gid = dict()
gid_to_iid = dict()
holo_count = len(data)

for gid, iid, names in data:
	if iid:
		gid_to_iid[gid] = iid
	for name in names:
		name_to_gid[name] = gid
